name: Release with commit

on:
  tags:

jobs:
  release-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # "Build" the files
      - name: prepare files to be compresses
        run: mkdir -p toCompress/dist; cp test_file_1.txt toCompress; cp test_file_3.txt toCompress; cp foo/bar/*.ts toCompress/dist
      # tar the files
      - name: tar the files
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            ./toCompress
          outPath: ${{ github.ref_name }}.tar.gz
      # create a release with the tar as a file
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.ref_name }}.tar.gz