name: Release with commit

on:
  push:
    tags:
      - '**'

jobs:
  release-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # "Build" the files
      - name: prepare files to be compresses
        run: |
          mkdir -p ${{ github.ref_name }}/dist
          cp test_file_1.txt ${{ github.ref_name }}
          cp test_file_3.txt ${{ github.ref_name }}
          cp foo/bar/*.ts ${{ github.ref_name }}/dist
      # tar the files
      - name: tar the files
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            ./${{ github.ref_name }}
          outPath: ${{ github.ref_name }}.tgz

      - name: package helm chart
        run: helm package anvil/ -d deploy/helm/

      # create a release with the tar as a file
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.ref_name }}.tgz
            deploy/helm/anvil*.tgz